name: Publish to npm

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - run: npm ci
      - run: npm run check
      - run: npm run build
      - name: Publish prerelease to npm
        if: github.event.release.prerelease == true
        run: npm publish --access public --tag next

      - name: Publish latest to npm
        if: github.event.release.prerelease == false
        run: npm publish --access public
